### ISSUE TITLE
adam-shell does not allow additional jars via Spark jars argument

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1349]
If I have this right, `adam-shell` does not allow additional jars via Spark `--jars` argument
```bash
$ adam-shell --jars my-jar.jar
...
scala> import org.bdgenomics.adam.rdd.ADAMContext
<console>:24: error: object bdgenomics is not a member of package org
       import org.bdgenomics.adam.rdd.ADAMContext
                  ^
```

`adam-shell` uses `--jars` to specify the ADAM cli jar
```bash
# submit the job to Spark
"$SPARK_SHELL" \
    --conf spark.serializer=org.apache.spark.serializer.KryoSerializer \
    --conf spark.kryo.registrator=org.bdgenomics.adam.serialization.ADAMKryoRegistrator \
    --jars ${ADAM_CLI_JAR} \
    "$@"
```

**Comment by fnothaft** [comment]
IIRC, you can only have `--jars`once, and first one wins.

**Comment by heuermh** [comment]
Right, so how do we fix it?  :)

**Comment by fnothaft** [comment]
Well, I can't promise an answer that you'll like, but I'd say either we mark that as a won't fix, or we parse out a `--jars` argument in the `bin/adam-submit` script.

**Comment by heuermh** [comment]
If one tries to cheat by specifying a custom jar and the adam fat jar (here coming from a homebrew installation) in `--jars`, it appears ok for a while but does not work out in the end
```
$ adam-shell --jars target/dsh-bio-adam-1.0-SNAPSHOT.jar:/usr/local/Cellar/adam/0.21.0/libexec/repo/adam_2.11-0.21.0.jar
Using SPARK_SHELL=/usr/local/bin/spark-shell
...
scala> import org.dishevelled.bio.adam.DishevelledAdamContext
import org.dishevelled.bio.adam.DishevelledAdamContext

scala> import org.bdgenomics.adam.rdd.ADAMContext
import org.bdgenomics.adam.rdd.ADAMContext

scala> val dac = new DishevelledAdamContext(sc)
dac: org.dishevelled.bio.adam.DishevelledAdamContext = org.dishevelled.bio.adam.DishevelledAdamContext@4a977146

scala> val features = dac.loadGff3("/Users/heuermh/working/adam/adam-core/src/test/resources/dvl1.200.gff3")
features: org.bdgenomics.adam.rdd.feature.FeatureRDD = FeatureRDD(MapPartitionsRDD[1] at map at DishevelledAdamContext.java:122,null)

scala> features.rdd.first
17/01/12 13:22:01 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.RuntimeException: Stream '/jars/adam_2.11-0.21.0.jar' was not found.
	at org.apache.spark.network.client.TransportResponseHandler.handle(TransportResponseHandler.java:222)
	at org.apache.spark.network.server.TransportChannelHandler.channelRead0(TransportChannelHandler.java:121)
	at org.apache.spark.network.server.TransportChannelHandler.channelRead0(TransportChannelHandler.java:51)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at org.apache.spark.network.util.TransportFrameDecoder.channelRead(TransportFrameDecoder.java:85)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by fnothaft** [comment]
I am labeling this as a won't fix for now. @heuermh please review and reopen if you disagree.

**Comment by heuermh** [comment]
Yes, this is fine to close.  I've updated the docs downstream to use
``` bash
$ spark-shell \
    --conf spark.serializer=org.apache.spark.serializer.KryoSerializer \
    --conf spark.kryo.registrator=MyKryoRegistrator \
    --jars my-fat-jar.jar
```
instead of `adam-submit`.

**Comment by fnothaft** [comment]
Thanks @heuermh!
