### ISSUE TITLE
Runtime conflicts in transitive versions of Guava dependency

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1350]
More of a tracking issue than anything else; something to investigate before the next ADAM release.

Spark 2.1.0 and ADAM 0.21.0 and an explicit dependency on Guava version 19.0 results in runtime conflicts
```
$ adam-shell --jars dsh-bio-adam-1.0-SNAPSHOT.jar:/usr/local/Cellar/adam/0.21.0/libexec/repo/adam_2.11-0.21.0.jar
...
scala> val features = dac.loadGff3("dvl1.200.gff3")
java.lang.NoSuchMethodError: com.google.common.base.Splitter.splitToList(Ljava/lang/CharSequence;)Ljava/util/List;
  at org.dishevelled.bio.feature.Gff3Record.valueOf(Gff3Record.java:287)
  at org.dishevelled.bio.feature.Gff3Reader$Gff3LineProcessor.processLine(Gff3Reader.java:112)
  at com.google.common.io.CharStreams.readLines(CharStreams.java:369)
  at org.dishevelled.bio.feature.Gff3Reader.stream(Gff3Reader.java:77)
  at org.dishevelled.bio.feature.Gff3Reader.read(Gff3Reader.java:61)
  at org.dishevelled.bio.adam.DishevelledAdamContext.loadGff3(DishevelledAdamContext.java:121)
  ... 48 elided
```

**Comment by heuermh** [comment]
Closing as WontFix, not much we can do on this one until all upstream gets it right.
