### ISSUE TITLE
Off-by-1 error in FASTQ InputFormat start positioning code

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1383]
See: https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/java/org/bdgenomics/adam/io/SingleFastqInputFormat.java#L65. Causes an AIOOBE:

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.bdgenomics.adam.io.SingleFastqInputFormat$SingleFastqRecordReader.checkBuffer(SingleFastqInputFormat.java:66)
	at org.bdgenomics.adam.io.FastqRecordReader.positionAtFirstRecord(FastqRecordReader.java:169)
	at org.bdgenomics.adam.io.FastqRecordReader.<init>(FastqRecordReader.java:126)
	at org.bdgenomics.adam.io.SingleFastqInputFormat$SingleFastqRecordReader.<init>(SingleFastqInputFormat.java:49)
	at org.bdgenomics.adam.io.SingleFastqInputFormat.createRecordReader(SingleFastqInputFormat.java:107)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:156)
```

This bug is in both the single and interleaved code.

**Comment by A-Tsai** [comment]
I found it happens when the first character of the block accessed by FileSplit is '\n'. At that scenario, bufferLength=0 and buffer is empty. It causes an exception due to ArrayIndexOutOfBounds because try to get buffer.getBytes()[0] in Line 66 on SingleFastqInputFormat.java. 
if we can remove '=' in Line 65 of SingleFastqInputFormat.java when checking "bufferLength >= 0", the issue can be solved. I'm not sure it is a right solution or not, but it works on my program.

**Comment by heuermh** [comment]
Thank you for the feedback, @A-Tsai
