### ISSUE TITLE
Can't merge BAM files containing the same sample

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1663]
We outlawed this in our glob loader code. However, this comes up if you want to do something like load in BAM files that are split out by sample. I had a benchmarking workflow where I had split a single aligned dataset into a single file per chromosome for debug, and got this on load:

```
User class threw exception: java.lang.IllegalArgumentException: requirement failed: Read group dictionary contains multiple samples with identical read group names.
java.lang.IllegalArgumentException: requirement failed: Read group dictionary contains multiple samples with identical read group names.
	at scala.Predef$.require(Predef.scala:233)
	at org.bdgenomics.adam.models.RecordGroupDictionary.<init>(RecordGroupDictionary.scala:85)
	at org.bdgenomics.adam.models.RecordGroupDictionary.$plus$plus(RecordGroupDictionary.scala:97)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadBam$1$$anonfun$13.apply(ADAMContext.scala:1485)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadBam$1$$anonfun$13.apply(ADAMContext.scala:1484)
```

**Comment by heuermh** [comment]
I may have mentioned this before, but I ran into the other case, where I have BAM files for 450 samples that all re-use the same read group names.  I didn't come up with a good way to handle this.  While including all reads from all samples in the same RDD perhaps doesn't make a lot of sense, including reads overlapping a region of interest across all samples certainly does.
