### ISSUE TITLE
Exporting non-reference genotype likelihoods to VCF appears to fail for triploid sites

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1776]
Happens when exporting CNV-aware joint genotyped VCF from Avocado:

```
java.lang.ArrayIndexOutOfBoundsException: 3
	at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$nonRefPls$2.apply$mcVI$sp(VariantContextConverter.scala:1032)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at org.bdgenomics.adam.converters.VariantContextConverter.nonRefPls(VariantContextConverter.scala:1031)
	at org.bdgenomics.adam.converters.VariantContextConverter.extractGenotypeLikelihoods(VariantContextConverter.scala:1060)
	at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$55.apply(VariantContextConverter.scala:1101)
	at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$55.apply(VariantContextConverter.scala:1101)
	at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$93.apply(VariantContextConverter.scala:2218)
	at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$93.apply(VariantContextConverter.scala:2216)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.bdgenomics.adam.converters.VariantContextConverter.org$bdgenomics$adam$converters$VariantContextConverter$$convert$4(VariantContextConverter.scala:2215)
	at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$makeGenotypeExtractFn$1.apply(VariantContextConverter.scala:2289)
	at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$makeGenotypeExtractFn$1.apply(VariantContextConverter.scala:2289)
	at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$convert$4.apply(VariantContextConverter.scala:2305)
	at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$convert$4.apply(VariantContextConverter.scala:2305)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.bdgenomics.adam.converters.VariantContextConverter.convert(VariantContextConverter.scala:2305)
	at org.bdgenomics.adam.rdd.variant.VariantContextRDD$$anonfun$saveAsVcf$1$$anonfun$2.apply(VariantContextRDD.scala:279)
	at org.bdgenomics.adam.rdd.variant.VariantContextRDD$$anonfun$saveAsVcf$1$$anonfun$2.apply(VariantContextRDD.scala:278)
```

**Comment by heuermh** [comment]
Closing as WontFix
