### ISSUE TITLE
Issue while using Sorting option

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/adam#1791]
HI,
I used cannoli for alignment:
Data :   SRR1517848_1.fastq , SRR1517848_.fastq

I used this command to make interleaved fastq :  ./cannoli-submit interleaveFastq   >   SRR1517848.fastq

Then I use this command for alignment :  ./cannoli-submit --driver-memory 3g --executor-memory 10g -- bwa -bwa_path /home/rokshan.jahan/adamproject/bwa-master/bwa -single hdfs://ip-10-48-3-5.ips.local:8020/genomics/cannoli_test/SRR1517848.fastq hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1517848.adam SRR1517848 -index /home/rokshan.jahan/adamproject/reference/ref/Homo_sapiens_assembly38.fasta  -sequence_dictionary hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/data/Homo_sapiens_assembly38.dict -force_load_ifastq

I got the output successfully in adam format :  SRR1517848.adam 

 I run adam command on this file :

./adam-submit transformAlignments hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1517848.adam hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1517848_new.adam -sort_reads -mark_duplicate_reads -recalibrate_base_qualities

Its giving me this error :

HLA-DRB1*16:02:01->11005, 3365}.
        at scala.Predef$.require(Predef.scala:233)
        at org.bdgenomics.adam.rdd.read.AlignmentRecordRDD$$anonfun$sortReadsByReferencePositionAndIndex$1$$anonfun$apply$10.apply(AlignmentRecordRDD.scala:918)
        at org.bdgenomics.adam.rdd.read.AlignmentRecordRDD$$anonfun$sortReadsByReferencePositionAndIndex$1$$anonfun$apply$10.apply(AlignmentRecordRDD.scala:915)
        at org.apache.spark.rdd.RDD$$anonfun$keyBy$1$$anonfun$apply$56.apply(RDD.scala:1492)
        at org.apache.spark.rdd.RDD$$anonfun$keyBy$1$$anonfun$apply$56.apply(RDD.scala:1492)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at org.apache.spark.util.random.SamplingUtils$.reservoirSampleAndCount(SamplingUtils.scala:42)
        at org.apache.spark.RangePartitioner$$anonfun$9.apply(Partitioner.scala:261)
        at org.apache.spark.RangePartitioner$$anonfun$9.apply(Partitioner.scala:259)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$22.apply(RDD.scala:745)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$22.apply(RDD.scala:745)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Any suggestion will be really helpful.

Thanks

**Comment by fnothaft** [comment]
Hi @Rokshan2016! This issue means that there was a read in your file that had a contig name that wasn't in your sequence dictionary. Do you still have the full error message? It should contain the contig name for the offending read.

**Comment by fnothaft** [comment]
I don't think there's more action here; please reopen if needed.
