### ISSUE TITLE
tests/testthat.R failed on git head

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1799]
```
$ mvn -Pr package
...
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... NONE
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
  	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
  	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
  	at java.lang.Thread.run(Thread.java:745)
  Error in handleErrors(returnStatus, conn) :
  Calls: test_check ... sparkR.newJObject -> newJObject -> invokeJava -> handleErrors
  testthat results ================================================================
  OK: 0 SKIPPED: 0 FAILED: 0
  Execution halted
* checking PDF version of manual ... OK
* DONE

Status: 1 ERROR, 2 WARNINGs, 3 NOTEs
```

**Comment by heuermh** [comment]
Closing as Invalid.

Forgot the magick incantations
```
$ ASSEMBLY_DIR=`pwd`/adam-assembly/target/
$ ASSEMBLY_JAR="$(ls -1 "$ASSEMBLY_DIR" | grep "^adam[0-9A-Za-z\_\.-]*\.jar$" | grep -v javadoc | grep -v sources || true)"
$ export SPARKR_SUBMIT_ARGS="--jars ${ASSEMBLY_DIR}/${ASSEMBLY_JAR} --driver-class-path ${ASSEMBLY_DIR}/${ASSEMBLY_JAR} sparkr-shell"
```
