### ISSUE TITLE
adam files with outdated formats throw FileNotFoundException

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1804]
```
scala> val x = sc.loadGenotypes("/data/platinum/analysis/NA12878_pedigree.gt.adam")
java.io.FileNotFoundException: Couldn't find any files matching /data/platinum/analysis/NA12878_pedigree.gt.adam
  at org.bdgenomics.adam.rdd.ADAMContext.getFsAndFilesWithFilter(ADAMContext.scala:1354)
  at org.bdgenomics.adam.rdd.ADAMContext.loadAvroSamples(ADAMContext.scala:1187)
  at org.bdgenomics.adam.rdd.ADAMContext.loadParquetGenotypes(ADAMContext.scala:2161)
  at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadGenotypes$1.apply(ADAMContext.scala:2814)
  at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadGenotypes$1.apply(ADAMContext.scala:2809)
  at scala.Option.fold(Option.scala:158)
  at org.apache.spark.rdd.Timer.time(Timer.scala:48)
  at org.bdgenomics.adam.rdd.ADAMContext.loadGenotypes(ADAMContext.scala:2807)
  ... 50 elided

```

**Comment by fnothaft** [comment]
We've generally treated this as a won't fix.

**Comment by akmorrow13** [comment]
Closing with https://github.com/bigdatagenomics/adam/pull/1805
