### ISSUE TITLE
loadFastq with paired gzipped FASTQ files fails via s3a URLs

### ISSUE THREAD

**Issue by judell-nmdp** [bigdatagenomics/adam#1855]
val reads = sc.loadFastq("s3a://F1.fastq.gz", Some("s3a://F2.fastq.gz"))

java.lang.IllegalArgumentException: Fastq 1 (s3a://F1.fastq.gz) has 55618449 reads, fastq 2 (s3a://F2.fastq.gz) has 55618451 reads
  at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadPairedFastq$1.apply(ADAMContext.scala:1899)
  at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadPairedFastq$1.apply(ADAMContext.scala:1876)
  at scala.Option.fold(Option.scala:158)
  at org.apache.spark.rdd.Timer.time(Timer.scala:48)
  at org.bdgenomics.adam.rdd.ADAMContext.loadPairedFastq(ADAMContext.scala:1876)
  at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadFastq$1$$anonfun$apply$10.apply(ADAMContext.scala:1852)
  at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadFastq$1$$anonfun$apply$10.apply(ADAMContext.scala:1851)
  at scala.Option.fold(Option.scala:158)
  at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadFastq$1.apply(ADAMContext.scala:1851)
  at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadFastq$1.apply(ADAMContext.scala:1851)
  at scala.Option.fold(Option.scala:158)
  at org.apache.spark.rdd.Timer.time(Timer.scala:48)
  at org.bdgenomics.adam.rdd.ADAMContext.loadFastq(ADAMContext.scala:1845)
  ... 51 elided

**Comment by judell-nmdp** [comment]
Update: the following command worked -

val reads = sc.loadFastq("hdfs:///F1.fastq.gz", Some("hdfs:///F2.fastq.gz"))

Using emr-5.10.0

**Comment by heuermh** [comment]
I will work to find a small test case.  I wonder if s3a pads or otherwise modifies the end of a gzipped file?

**Comment by jpdna** [comment]
Have we only seen this problem with the specific examples files mentioned above, or is it a common problem when reading gzipped fastq or other formats?
https://issues.apache.org/jira/browse/SPARK-5250 mentions file corruption of gzipped files.

If this is rare, I'd be curious to confirm the read count on a local unzipped copy of these files, gzip and re-upload to S3, and see if the problem reproduces.

**Comment by heuermh** [comment]
I haven't been able to reproduce this with a test case, closing as CannotReproduce
