### ISSUE TITLE
Read the Docs build failing with TypeError: super() argument 1 must be type, not None

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1917]
```
...
python2.7 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest
python /home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/bin/pip install --use-wheel --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/adam/.cache/pip Pygments==2.2.0 setuptools==37.0.0 docutils==0.13.1 mock==1.0.1 pillow==2.6.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0 sphinx==1.6.5 sphinx-rtd-theme<0.3 readthedocs-sphinx-ext<0.6
python /home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/adam/.cache/pip -rdocs/requirements.txt
Collecting sphinxcontrib-fulltoc (from -r docs/requirements.txt (line 1))
  Downloading sphinxcontrib-fulltoc-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    
    Installed /tmp/pip-build-MmJ1B1/sphinxcontrib-fulltoc/.eggs/pbr-3.1.1-py2.7.egg
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-build-MmJ1B1/sphinxcontrib-fulltoc/.eggs/pbr-3.1.1-py2.7.egg/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-build-MmJ1B1/sphinxcontrib-fulltoc/.eggs/pbr-3.1.1-py2.7.egg/pbr/util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "/tmp/pip-build-MmJ1B1/sphinxcontrib-fulltoc/.eggs/pbr-3.1.1-py2.7.egg/pbr/util.py", line 569, in wrap_commands
        cmdclass = ep.resolve()
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/sphinx/setup_command.py", line 23, in <module>
        from sphinx.application import Sphinx
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 33, in <module>
        from sphinx.environment import BuildEnvironment
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 46, in <module>
        from sphinx.util.websupport import is_commentable
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/sphinx/util/websupport.py", line 11, in <module>
        from sphinxcontrib.websupport.utils import is_commentable  # NOQA
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/lib/python2.7/site-packages/sphinxcontrib/websupport/__init__.py", line 15, in <module>
        from sphinxcontrib.websupport.core import WebSupport  # NOQA
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/lib/python2.7/site-packages/sphinxcontrib/websupport/core.py", line 17, in <module>
        from jinja2 import Environment, FileSystemLoader
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/jinja2/__init__.py", line 33, in <module>
        from jinja2.environment import Environment, Template
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/jinja2/environment.py", line 15, in <module>
        from jinja2 import nodes
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/jinja2/nodes.py", line 19, in <module>
        from jinja2.utils import Markup
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/jinja2/utils.py", line 486, in <module>
        MutableMapping.register(LRUCache)
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/lib/python2.7/abc.py", line 109, in register
        if issubclass(subclass, cls):
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/lib/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/typing.py", line 1249, in __subclasscheck__
        return super(GenericMeta, self).__subclasscheck__(cls)
    TypeError: super() argument 1 must be type, not None
    error in setup command: Error parsing /tmp/pip-build-MmJ1B1/sphinxcontrib-fulltoc/setup.cfg: TypeError: super() argument 1 must be type, not None
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-MmJ1B1/sphinxcontrib-fulltoc/
Command time: 4s Return: 1
```

**Comment by heuermh** [comment]
@akmorrow13 With #1916 merged, I'm still seeing the same error:
```
...
python /home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/adam/.cache/pip -rdocs/requirements.txt
Collecting sphinxcontrib-fulltoc (from -r docs/requirements.txt (line 1))
  Using cached sphinxcontrib-fulltoc-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    
    Installed /tmp/pip-build-GI0ioA/sphinxcontrib-fulltoc/.eggs/pbr-3.1.1-py2.7.egg
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-build-GI0ioA/sphinxcontrib-fulltoc/.eggs/pbr-3.1.1-py2.7.egg/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-build-GI0ioA/sphinxcontrib-fulltoc/.eggs/pbr-3.1.1-py2.7.egg/pbr/util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "/tmp/pip-build-GI0ioA/sphinxcontrib-fulltoc/.eggs/pbr-3.1.1-py2.7.egg/pbr/util.py", line 569, in wrap_commands
        cmdclass = ep.resolve()
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/sphinx/setup_command.py", line 23, in <module>
        from sphinx.application import Sphinx
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 33, in <module>
        from sphinx.environment import BuildEnvironment
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 46, in <module>
        from sphinx.util.websupport import is_commentable
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/sphinx/util/websupport.py", line 11, in <module>
        from sphinxcontrib.websupport.utils import is_commentable  # NOQA
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/lib/python2.7/site-packages/sphinxcontrib/websupport/__init__.py", line 15, in <module>
        from sphinxcontrib.websupport.core import WebSupport  # NOQA
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/lib/python2.7/site-packages/sphinxcontrib/websupport/core.py", line 17, in <module>
        from jinja2 import Environment, FileSystemLoader
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/jinja2/__init__.py", line 33, in <module>
        from jinja2.environment import Environment, Template
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/jinja2/environment.py", line 15, in <module>
        from jinja2 import nodes
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/jinja2/nodes.py", line 19, in <module>
        from jinja2.utils import Markup
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/jinja2/utils.py", line 486, in <module>
        MutableMapping.register(LRUCache)
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/lib/python2.7/abc.py", line 109, in register
        if issubclass(subclass, cls):
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/lib/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/home/docs/checkouts/readthedocs.org/user_builds/adam/envs/latest/local/lib/python2.7/site-packages/typing.py", line 1249, in __subclasscheck__
        return super(GenericMeta, self).__subclasscheck__(cls)
    TypeError: super() argument 1 must be type, not None
    error in setup command: Error parsing /tmp/pip-build-GI0ioA/sphinxcontrib-fulltoc/setup.cfg: TypeError: super() argument 1 must be type, not None
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-GI0ioA/sphinxcontrib-fulltoc/
Command time: 6s Return: 1
```

**Comment by heuermh** [comment]
@akmorrow13 Can you take another look at this? We need it for the 0.24.0 release.

**Comment by fnothaft** [comment]
This is https://github.com/sphinx-doc/sphinx/issues/3976. PR on the way...

**Comment by fnothaft** [comment]
From the build,
```
Collecting sphinx==1.6.5
  Downloading Sphinx-1.6.5-py2.py3-none-any.whl (1.9MB)
```

Grrr...
