### ISSUE TITLE
NotSerializableException: com.netflix.servo.monitor.LongGauge

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1952]
```
org.apache.spark.SparkException: Task not serializable
  at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:340)
  at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:330)
  at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:156)
  at org.apache.spark.SparkContext.clean(SparkContext.scala:2294)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2068)
  at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1354)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.take(RDD.scala:1327)
  at org.apache.spark.rdd.InstrumentedRDD$$anonfun$take$1.apply(InstrumentedRDD.scala:274)
  at org.apache.spark.rdd.Timer$$anonfun$time$1.apply(Timer.scala:52)
  at org.apache.spark.rdd.Timer$$anonfun$time$1.apply(Timer.scala:48)
  at scala.Option.fold(Option.scala:158)
  at org.apache.spark.rdd.Timer.time(Timer.scala:48)
  at org.apache.spark.rdd.InstrumentedRDD$.recordOperation(InstrumentedRDD.scala:346)
  at org.apache.spark.rdd.InstrumentedRDD.take(InstrumentedRDD.scala:273)
  at org.bdgenomics.adam.util.ADAMShell$.printFilters(ADAMShell.scala:47)
  ... 52 elided
Caused by: java.io.NotSerializableException: com.netflix.servo.monitor.LongGauge
Serialization stack:
	- object not serializable (class: com.netflix.servo.monitor.LongGauge, value: NumberGauge{config=MonitorConfig{name=statistic, tags=statistic=DriverTotalTime,GAUGE, policy=DefaultPublishingPolicy}, number=1382323904})
	- element of array (index: 5)
	- array (class [Ljava.lang.Object;, size 16)
	- field (class: scala.collection.mutable.ArrayBuffer, name: array, type: class [Ljava.lang.Object;)
	- object (class scala.collection.mutable.ArrayBuffer, ArrayBuffer(org.bdgenomics.utils.instrumentation.ServoTimer$LongValueStatMonitor@63b4b582, org.bdgenomics.utils.instrumentation.ServoTimer$LongValueStatMonitor@3bf4c059, org.bdgenomics.utils.instrumentation.ServoTimer$LongValueStatMonitor@33f80d9d, org.bdgenomics.utils.instrumentation.ServoTimer$ConditionalGauge@160c1d08, org.bdgenomics.utils.instrumentation.ServoTimer$ConditionalGauge@349f4bb0, NumberGauge{config=MonitorConfig{name=statistic, tags=statistic=DriverTotalTime,GAUGE, policy=DefaultPublishingPolicy}, number=1382323904}))
	- field (class: org.bdgenomics.utils.instrumentation.ServoTimer, name: subMonitors, type: interface scala.collection.mutable.Buffer)
	- object (class org.bdgenomics.utils.instrumentation.ServoTimer, org.bdgenomics.utils.instrumentation.ServoTimer@7dd9423d)
	- writeObject data (class: java.util.concurrent.ConcurrentHashMap)
	- object (class java.util.concurrent.ConcurrentHashMap, {/count at <console>:33(3,true)=org.bdgenomics.utils.instrumentation.ServoTimer@7dd9423d, /Load Variants(1,false)=org.bdgenomics.utils.instrumentation.ServoTimer@4e729324, /map at ADAMContext.scala:1287(2,true)=org.bdgenomics.utils.instrumentation.ServoTimer@2cf0f7e7, /map at ADAMContext.scala:1287(2,true)/function call(0,false)=org.bdgenomics.utils.instrumentation.ServoTimer@10193ef})
	- field (class: org.bdgenomics.utils.instrumentation.ServoTimers, name: timerMap, type: class java.util.concurrent.ConcurrentHashMap)
	- object (class org.bdgenomics.utils.instrumentation.ServoTimers, org.bdgenomics.utils.instrumentation.ServoTimers@d56175f0)
	- field (class: org.apache.spark.util.LegacyAccumulatorWrapper, name: initialValue, type: class java.lang.Object)
	- object (class org.apache.spark.util.LegacyAccumulatorWrapper, LegacyAccumulatorWrapper(id: 202, name: None, value: org.bdgenomics.utils.instrumentation.ServoTimers@d56175f0))
	- field (class: org.apache.spark.Accumulable, name: newAcc, type: class org.apache.spark.util.LegacyAccumulatorWrapper)
	- object (class org.apache.spark.Accumulable, org.bdgenomics.utils.instrumentation.ServoTimers@d56175f0)
	- field (class: org.bdgenomics.utils.instrumentation.MetricsRecorder, name: accumulable, type: class org.apache.spark.Accumulable)
	- object (class org.bdgenomics.utils.instrumentation.MetricsRecorder, org.bdgenomics.utils.instrumentation.MetricsRecorder@47e51a7a)
	- field (class: scala.Some, name: x, type: class java.lang.Object)
	- object (class scala.Some, Some(org.bdgenomics.utils.instrumentation.MetricsRecorder@47e51a7a))
	- field (class: org.apache.spark.rdd.FunctionRecorder, name: recorder, type: class scala.Option)
	- object (class org.apache.spark.rdd.FunctionRecorder, org.apache.spark.rdd.FunctionRecorder@7d3b22f8)
	- field (class: org.apache.spark.rdd.InstrumentedRDD$$anonfun$map$1$$anonfun$apply$4, name: recorder$1, type: class org.apache.spark.rdd.FunctionRecorder)
	- object (class org.apache.spark.rdd.InstrumentedRDD$$anonfun$map$1$$anonfun$apply$4, <function1>)
	- field (class: org.apache.spark.rdd.RDD$$anonfun$map$1$$anonfun$apply$5, name: cleanF$1, type: interface scala.Function1)
	- object (class org.apache.spark.rdd.RDD$$anonfun$map$1$$anonfun$apply$5, <function3>)
	- field (class: org.apache.spark.rdd.MapPartitionsRDD, name: f, type: interface scala.Function3)
	- object (class org.apache.spark.rdd.MapPartitionsRDD, MapPartitionsRDD[17] at map at ADAMContext.scala:1287)
	- field (class: org.apache.spark.rdd.RDD$$anonfun$take$1, name: $outer, type: class org.apache.spark.rdd.RDD)
	- object (class org.apache.spark.rdd.RDD$$anonfun$take$1, <function0>)
	- field (class: org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29, name: $outer, type: class org.apache.spark.rdd.RDD$$anonfun$take$1)
	- object (class org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29, <function1>)
  at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
  at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
  at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
  at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:337)
  ... 69 more
```

**Comment by heuermh** [comment]
Closing as UnableToReproduce.
