### ISSUE TITLE
NoSuchMethodError: shaded.parquet.org.apache.thrift.EncodingUtils.setBit(BIZ)B

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#2157]
Runtime failure when running against Spark 2.2.0, not exactly sure where `shaded.parquet` package is coming from.

`org.bdgenomics.adam.shaded` is our shaded `org.apache.parquet.avro` package, from `adam-assembly` module.

```
$ export SPARK_HOME=/opt/cloudera/parcels/SPARK2-2.2.0.cloudera1-1.cdh5.12.0.p0.142354/lib/spark2/

$ adam-submit ... -- transformAlignments sample.bam sample.alignments.adam
...
Caused by: java.lang.NoSuchMethodError: shaded.parquet.org.apache.thrift.EncodingUtils.setBit(BIZ)B
	at org.apache.parquet.format.PageHeader.setUncompressed_page_sizeIsSet(PageHeader.java:325)
	at org.apache.parquet.format.PageHeader.<init>(PageHeader.java:216)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.newDataPageHeader(ParquetMetadataConverter.java:1071)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.writeDataPageHeader(ParquetMetadataConverter.java:1059)
	at org.apache.parquet.hadoop.ColumnChunkPageWriteStore$ColumnChunkPageWriter.writePage(ColumnChunkPageWriteStore.java:103)
	at org.apache.parquet.column.impl.ColumnWriterV1.writePage(ColumnWriterV1.java:147)
	at org.apache.parquet.column.impl.ColumnWriterV1.accountForValueWritten(ColumnWriterV1.java:106)
	at org.apache.parquet.column.impl.ColumnWriterV1.write(ColumnWriterV1.java:200)
	at org.apache.parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.addBinary(MessageColumnIO.java:469)
	at org.bdgenomics.adam.shaded.org.apache.parquet.avro.AvroWriteSupport.writeValueWithoutConversion(AvroWriteSupport.java:346)
	at org.bdgenomics.adam.shaded.org.apache.parquet.avro.AvroWriteSupport.writeValue(AvroWriteSupport.java:278)
	at org.bdgenomics.adam.shaded.org.apache.parquet.avro.AvroWriteSupport.writeRecordFields(AvroWriteSupport.java:191)
	at org.bdgenomics.adam.shaded.org.apache.parquet.avro.AvroWriteSupport.write(AvroWriteSupport.java:165)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:128)
	at org.apache.parquet.hadoop.ParquetRecordWriter.write(ParquetRecordWriter.java:182)
	at org.apache.parquet.hadoop.ParquetRecordWriter.write(ParquetRecordWriter.java:44)
	at org.apache.spark.rdd.InstrumentedRecordWriter$$anonfun$write$1.apply$mcV$sp(InstrumentedOutputFormat.scala:55)
	at org.apache.spark.rdd.InstrumentedRecordWriter$$anonfun$write$1.apply(InstrumentedOutputFormat.scala:55)
	at org.apache.spark.rdd.InstrumentedRecordWriter$$anonfun$write$1.apply(InstrumentedOutputFormat.scala:55)
	at scala.Option.fold(Option.scala:158)
	at org.apache.spark.rdd.Timer.time(Timer.scala:48)
	at org.apache.spark.rdd.InstrumentedRecordWriter.write(InstrumentedOutputFormat.scala:54)
	at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$$anonfun$4.apply(SparkHadoopMapReduceWriter.scala:148)
	at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$$anonfun$4.apply(SparkHadoopMapReduceWriter.scala:144)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1375)
	at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$.org$apache$spark$internal$io$SparkHadoopMapReduceWriter$$executeTask(SparkHadoopMapReduceWriter.scala:159)
	... 8 more
	Suppressed: java.lang.NoSuchMethodError: shaded.parquet.org.apache.thrift.EncodingUtils.setBit(BIZ)B
		at org.apache.parquet.format.PageHeader.setUncompressed_page_sizeIsSet(PageHeader.java:325)
		at org.apache.parquet.format.PageHeader.<init>(PageHeader.java:216)
		at org.apache.parquet.format.converter.ParquetMetadataConverter.newDataPageHeader(ParquetMetadataConverter.java:1071)
		at org.apache.parquet.format.converter.ParquetMetadataConverter.writeDataPageHeader(ParquetMetadataConverter.java:1059)
		at org.apache.parquet.hadoop.ColumnChunkPageWriteStore$ColumnChunkPageWriter.writePage(ColumnChunkPageWriteStore.java:103)
		at org.apache.parquet.column.impl.ColumnWriterV1.writePage(ColumnWriterV1.java:147)
		at org.apache.parquet.column.impl.ColumnWriterV1.flush(ColumnWriterV1.java:235)
		at org.apache.parquet.column.impl.ColumnWriteStoreV1.flush(ColumnWriteStoreV1.java:122)
		at org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:172)
		at org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:114)
		at org.apache.parquet.hadoop.ParquetRecordWriter.close(ParquetRecordWriter.java:165)
		at org.apache.spark.rdd.InstrumentedRecordWriter.close(InstrumentedOutputFormat.scala:60)
		at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$$anonfun$1.apply$mcV$sp(SparkHadoopMapReduceWriter.scala:163)
		at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1384)
		... 9 more
```

**Comment by heuermh** [comment]
Fixed by #2255
