### ISSUE TITLE
StackOverflowError when saving to BAM in adam-shell

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#2186]
Not sure why this is happening now in the shell, this use case should be well covered by unit tests
```
$ adam-shell -i rw_bam_adam.scala
Using SPARK_SHELL=/usr/local/bin/spark-shell
19/07/16 15:51:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Spark context Web UI available at http://192.168.1.149:4040
Spark context available as 'sc' (master = local[*], app id = local-1563310295949).
Spark session available as 'spark'.
java.lang.StackOverflowError
  at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:97)
  at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:540)
  at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:75)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
  at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
  at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
...
```

rw_bam_adam.scala
```scala
import org.bdgenomics.adam.rdd.ADAMContext._
val alignments = sc.loadBam(inputPath.get)
alignments.saveAsSam(outputPath.get, asSingleFile = true)
```

**Comment by heuermh** [comment]
Unable to reproduce on git head or with 0.28.0 release.
