### ISSUE TITLE
Bam files with no unmapped reads fails to sort

### ISSUE THREAD

**Issue by jamesthegiantpeach** [bigdatagenomics/adam#2242]
I have some exomes that I use for testing. One of them is from a mapped whole genome where I took a subset, reverted to fastq, and then removed unpaired reads. Looks like this resulted in there being no unmapped reads. 

Looks like [this](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentDataset.scala#L1036) code is where the error is coming from. Since the structure of unmapped reads is empty, it throws this error

```
Exception in thread "main" java.lang.UnsupportedOperationException: empty.max
	at scala.collection.TraversableOnce$class.max(TraversableOnce.scala:229)
	at scala.collection.AbstractTraversable.max(Traversable.scala:104)
	at org.bdgenomics.adam.rdd.read.AlignmentDataset$$anonfun$sortByReferencePositionAndIndex$1.apply(AlignmentDataset.scala:1036)
	at org.bdgenomics.adam.rdd.read.AlignmentDataset$$anonfun$sortByReferencePositionAndIndex$1.apply(AlignmentDataset.scala:1028)
	at scala.Option.fold(Option.scala:158)
	at org.apache.spark.rdd.Timer.time(Timer.scala:48)

```

Edit: Actually. I'm getting this error with simulated reads as well. Might be user error

**Comment by jamesthegiantpeach** [comment]
Sorry. More noise on my end. Typo error with file path and reference. It looks like the library will not complain about a required file not existing.

**Comment by heuermh** [comment]
Are there conditions we should be checking for in ADAM and are not?  We're relying on Hadoop-BAM and htsjdk upstream doing the right thing in a lot of BAM code paths, and that is not always a safe idea.
