### ISSUE TITLE
All of my samples fail due to adam erroneously thinking there are different numbers of reads in r1 and r2.

### ISSUE THREAD

**Issue by ghost** [bigdatagenomics/adam#2247]
Upon loading fastq files using adamcontext, I get the following error

```
Exception in thread "main" java.lang.IllegalArgumentException: Fastq 1 (s3a://bgi-concordance-studies/run190704NovaSeq_R1_A501.fastq.gz.corrected.fastq.err_barcode_removed.fixed.fastq.gz) has 1023782058 reads, fastq 2 (s3a://bgi-concordance-studies/run190704NovaSeq_R2_A501.fastq.gz.corrected.fastq.err_barcode_removed.fixed.fastq.gz) has 1023782057 reads
    at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadPairedFastq$1.apply(ADAMContext.scala:2536)
    at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadPairedFastq$1.apply(ADAMContext.scala:2513)
    at scala.Option.fold(Option.scala:158)
    at org.apache.spark.rdd.Timer.time(Timer.scala:48)
    at org.bdgenomics.adam.rdd.ADAMContext.loadPairedFastq(ADAMContext.scala:2513)
    at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadPairedFastqAsFragments$1.apply(ADAMContext.scala:3059)
    at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadPairedFastqAsFragments$1.apply(ADAMContext.scala:3059)
    at scala.Option.fold(Option.scala:158)
    at org.apache.spark.rdd.Timer.time(Timer.scala:48)
    at org.bdgenomics.adam.rdd.ADAMContext.loadPairedFastqAsFragments(ADAMContext.scala:3057)
    at org.myome.bigbioinf.Main$.main(Main.scala:39)
    at org.myome.bigbioinf.Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
    at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
    at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
    at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
    at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
    at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
At first I thought this was some kind of barcode problem. However, I seem to be getting this with almost any genome. I just tried NA12878 and got the same error. The true number of reads is 

1023782052

The reported r1 and r2 count are always off by a single read, but they're usually off by a few reads compared to the actual number. I typically get ground truth by counting the number of lines in the file and dividing by 4. 

I have no clue what is causing this. I have included small fastq files in your test suite and run the relevant tests over the fastq files. No errors. Bizarre.

**Comment by jamesthegiantpeach** [comment]
Here's another example with NA12878 

```
Exception in thread "main" java.lang.IllegalArgumentException: Fastq 1 (s3a://bgi-concordance-studies/stflr/na12878_1.fq.bgz) has 586878293 reads, fastq 2 (s3a://bgi-concordance-studies/stflr/na12878_2.fq.bgz) has 586878292 reads
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadPairedFastq$1.apply(ADAMContext.scala:2536)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadPairedFastq$1.apply(ADAMContext.scala:2513)
	at scala.Option.fold(Option.scala:158)
	at org.apache.spark.rdd.Timer.time(Timer.scala:48)
	at org.bdgenomics.adam.rdd.ADAMContext.loadPairedFastq(ADAMContext.scala:2513)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadPairedFastqAsFragments$1.apply(ADAMContext.scala:3059)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadPairedFastqAsFragments$1.apply(ADAMContext.scala:3059)
	at scala.Option.fold(Option.scala:158)
	at org.apache.spark.rdd.Timer.time(Timer.scala:48)
	at org.bdgenomics.adam.rdd.ADAMContext.loadPairedFastqAsFragments(ADAMContext.scala:3057)
	at org.myome.bigbioinf.Main$.main(Main.scala:39)
	at org.myome.bigbioinf.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by heuermh** [comment]
Damn, I was hoping it was something straightforward like a header regex issue.

I recently closed a similar issue https://github.com/bigdatagenomics/adam/issues/1855 because I could not replicate it on other samples.  That happened with a collaborator, so I no longer have access to that particular sample.

I assume that with `.bgz` extension these are Block gzipped (BGZF) files?  If so, support for splittable BZGF was added in https://github.com/bigdatagenomics/adam/pull/1609

Note that more generally, the FASTQ support in adam is not as robust as it might be elsewhere, such as in Biojava, which can handle line wraps and other odd formatting. E.g. https://github.com/bigdatagenomics/adam/pull/679

What do you know about `s3a:` vs `s3:` protocol in your use case?  I get confused by the various permutations of advice; as far as I know, on EMR it is best to use `s3:` with the EMR-provided client. 

https://stackoverflow.com/questions/33356041/technically-what-is-the-difference-between-s3n-s3a-and-s3/40872184#40872184

**Comment by jamesthegiantpeach** [comment]
Same! 

Ok yes that is the exact issue I am having. I can't actually reproduce this locally even with a minio server while using s3a URLs. It only appears with a full genome.

Yes they are block gzipped files. I am using a recent release so it should be fine.

I'll have to check out biojava never tried it. 

I am using S3 only so I was told that the best tool to use is s3a, but I don't know enough to make an intelligent decision here. Currently, I am not using EMR I am using the k8s spark-operator with s3a. I am not getting this issue with certain reads actually. I don't get these with bgiseq500 reads or reads that look like this 

```
@H06HDADXX130110:2:2116:3345:91806/1
GTTAGGGTTAGGGTTGGGTTAGGGTTAGGGTTAGGGTTAGGGGTAGGGTTAGGGTTAGGGGTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGGTAGGGCTAGGGTTAAGGGTAGGGTTAGCGAAAGGGCTGGGGTTAGGGGTGCGGGTACGCGTAGCATTAGGGCTAGAAGTAGGATCTGCAGTGCCTGACCGCGTCTGCGCGGCGACTGCCCAAAGCCTGGGGCCGACTCCAGGCTGAAGCTCAT
+
>=<=???>?>???=??>>8<?><=2=<===1194<?;:?>>?#3==>############################################################################
```

I am not totally sure though. It could have nothing to do with the fastq files. Is there a workaround for converting the fastq files to a different format prior to loading?

**Comment by jamesthegiantpeach** [comment]
Hmm. I'm going to try and run the same samples uncompressed and see if this narrows down the problem. It might be an issue with s3a and gzip corrupting the files. I first thought, maybe there's reads with the same names copied, but that should lead to an under count. It's always over counting.

**Comment by heuermh** [comment]
(oops, sorry, I accidently edited your above comment)

> I'll have to check out biojava never tried it. 

I wrote the Biojava FASTQ stuff, so while I know it is not the most efficient code, it is more robust to strangely formatted yet still valid FASTQ files.  The test suite

https://github.com/biojava/biojava/tree/master/biojava-genome/src/test/resources/org/biojava/nbio/genome/io/fastq

is shared among the other Bio* projects (well, Biopython and Bioperl at least, if I remember correctly).

I also wrote https://github.com/biojava/biojava-adam, which allows one to use Biojava to read FASTQ and convert to adam.  It does not scale well however in clustered environments, since the entire file is read into RAM on the master node.

> Is there a workaround for converting the fastq files to a different format prior to loading?

One could transform FASTQ into Parquet with ADAM, and then pull from that for analysis, although of course that goes through the same code path.

We want to add FASTQ support to Disq, but the thought was to migrate the FASTQ support from ADAM, so that also does not help.

If you can convert FASTQ to "unaligned BAM" format out of band, that might be your best bet.

**Comment by jamesthegiantpeach** [comment]
Ok i'll definitely give biojava a look. I'll try a pre-processing step with biojava-adam converter. I have a bunch of servers with a few hundred GB of ram.

It looks like there's an interleaved fastq converter and unaligned bam converter in cannoli. Would that be the best thing to use?

**Comment by heuermh** [comment]
Unaligned BAM is supported across ADAM, e.g. if you want the unaligned `Alignment` records
```scala
val alignments: AlignmentDataset = sc.loadAlignments("sample.unaligned.bam")
```
or unaligned read pairs (which we call `Fragment`s)
```scala
val fragments: FragmentDataset = sc.loadFragments("sample.unaligned.bam")
 // or
val fragments: FragmentDataset = sc.loadAlignments("sample.unaligned.bam").toFragments()
```
or unaligned reads
```
val reads: ReadDataset = sc.loadAlignments("sample.unaligned.bam").toReads()
```

**Comment by jamesthegiantpeach** [comment]
Ok so loadFragments would produce the same structure `sc.loadPairedFastqAsFragments(readFile1, readFile2)` ?

**Comment by heuermh** [comment]
Yep

**Comment by jamesthegiantpeach** [comment]
Confirming that this does not come up with gunzipped files. This for sure has something to do with s3a corrupting gzipped text files.
