### ISSUE TITLE
NoClassDefError org.apache.spark.AccumulableParam on Spark 3.0.0 preview

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#2250]
```
$ spark-submit --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.0.0-preview2
      /_/
                        
Using Scala version 2.12.10, OpenJDK 64-Bit Server VM, 1.8.0_242
Branch HEAD
Compiled by user yumwang on 2019-12-17T03:13:33Z
Revision bcadd5c3096109878fe26fb0d57a9b7d6fdaa257
Url https://gitbox.apache.org/repos/asf/spark.git
Type --help for more information.

$ adam-submit ...
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/AccumulableParam
	at org.bdgenomics.utils.cli.BDGSparkCommand.initializeMetrics(BDGCommand.scala:76)
	at org.bdgenomics.utils.cli.BDGSparkCommand.initializeMetrics$(BDGCommand.scala:68)
	at org.bdgenomics.adam.cli.TransformAlignments.initializeMetrics(TransformAlignments.scala:204)
	at org.bdgenomics.utils.cli.BDGSparkCommand.run(BDGCommand.scala:53)
	at org.bdgenomics.utils.cli.BDGSparkCommand.run$(BDGCommand.scala:46)
	at org.bdgenomics.adam.cli.TransformAlignments.run(TransformAlignments.scala:204)
	at org.bdgenomics.adam.cli.ADAMMain.apply(ADAMMain.scala:126)
	at org.bdgenomics.adam.cli.ADAMMain$.main(ADAMMain.scala:65)
	at org.bdgenomics.adam.cli.ADAMMain.main(ADAMMain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.AccumulableParam
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 21 more
```

**Comment by heuermh** [comment]
Fixed by #2255
