### ISSUE TITLE
loadBam cannot load BAM files hosted on SRA s3 archive

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#2295]
For example, in the COVID-19 Genome Sequence Dataset on the Registry of Open Data on AWS

https://registry.opendata.aws/ncbi-covid-19/

Several of the BAM formatted files in the `sra-src` directory have file extensions of `.bam.1`, e.g.
```
$ aws s3 ls s3://sra-pub-sars-cov2/sra-src/ERR4208260/ --no-sign-request
2020-08-08 23:08:02   47157308 PHEC_1B503.200417_NS552079_0030_AHNMCFBGXF.climb.public.bam.1

$ aws s3 ls s3://sra-pub-sars-cov2/sra-src/ERR4238198/ --no-sign-request
2020-08-08 21:20:51   23402442 ARTIC_ONT_EC6DB.sorted.bam.1

$ aws s3 ls s3://sra-pub-sars-cov2/sra-src/ERR4242916/ --no-sign-request
2020-08-12 05:39:15   11436653 LOND_D55C9.20200506_1544_X3_FAN40714_a0329ffb.climb.public.bam.1
```

```
scala> val alignments = sc.loadBam("LOND_D55C9.20200506_1544_X3_FAN40714_a0329ffb.climb.public.bam.1")
java.lang.IllegalArgumentException: requirement failed:
Did not find any BAM files at LOND_D55C9.20200506_1544_X3_FAN40714_a0329ffb.climb.public.bam.1.
  at scala.Predef$.require(Predef.scala:281)
  at org.bdgenomics.adam.rdd.ADAMContext.loadBam(ADAMContext.scala:2004)
```

Check at https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/FileExtensions.scala#L37

**Comment by heuermh** [comment]
Tracking support case #CAS-667747-M1J1T8 with SRA/NLM/NCBI over email.
