### ISSUE TITLE
error when saveAsPairedFastq files

### ISSUE THREAD

**Issue by vcaldara** [bigdatagenomics/adam#2350]
Hello
I have a problem with saving paired fastq files:
i use cannoli for allignement entire genomic data, when i only extracted one chromosome so when i try to save it in paired fastq files i get this error:

Exception in thread "main" java.lang.AssertionError: assertion failed: Different numbers of first- and second-reads: 578110 vs. 578130
        at scala.Predef$.assert(Predef.scala:223)
        at org.bdgenomics.adam.ds.read.AlignmentDataset.saveAsPairedFastq(AlignmentDataset.scala:1509)
        at org.bdgenomics.adam.ds.read.AlignmentDataset.saveAsFastq(AlignmentDataset.scala:1620)
        at org.bdgenomics.adam.cli.ADAM2Fastq.run(ADAM2Fastq.scala:98)

i looking for in the documentation like merge map and unmap reads, or duplicate unmap reads but i don't found anything.
any idea ?

**Comment by heuermh** [comment]
Hello @vcaldara!

You may filter the `AlignmentDataset` using any of the pre-defined filter methods
```
val alignments = ...
val paired = alignments.filterUnpairedReads()
paired.saveAsPairedFastq(...)
```
or provide your own, via Spark Dataset APIs
```
val alignments = ...
val paired = alignments.transformDataset(dataset => dataset.filter(...))
paired.saveAsPairedFastq(...)
```
or RDD APIs
```
val alignments = ...
val paired = alignments.transform((rdd: RDD[Alignment]) => rdd.filter(...))
paired.saveAsPairedFastq(...)
```

Hope this helps!

**Comment by heuermh** [comment]
Closing this issue as resolved, please reopen if necessary!
