### ISSUE TITLE
Avro.GenericData error with ADAM 0.12.0 on reading from ADAM file

### ISSUE THREAD

**Issue by pkondratyuk** [bigdatagenomics/adam#290]
We've built a simple program based on the adam-core API that reads from an ADAM file and tries to write a SAM file, and it compiles fine but for some reason fails at runtime with a strange-looking exception:

`java.lang.ClassCastException: org.apache.avro.generic.GenericData$Record cannot be cast to org.bdgenomics.adam.avro.ADAMRecord`

What could be going here? The code is below, it's pretty basic:

>>def main(args : Array[String])
{
        val adamFolder : String = "hdfs://test/user/root/testAdamFiles";
        val samFile : String = "/usr/local/adam/testSAM/file.sam";

>>val sc = new SparkContext("local", "Simple App", "/usr/lib/spark",
        List("/root/NetBeansProjects/mavenscala1/target/mavenscala1-1.0.jar"));

>>val adamContext : ADAMContext = new ADAMContext(sc);

>>val rddAdamRec : RDD[ADAMRecord] = adamContext.adamLoad(adamFolder);

>>val adamFunctions : ADAMRecordRDDFunctions = new ADAMRecordRDDFunctions(rddAdamRec);

>>adamFunctions.adamSAMSave(samFile, true); // save as SAM
}

**Comment by heuermh** [comment]
@pkondratyuk recent build changes (currently well past 0.12.0, we're now at version 0.18.1) should improve the situation for extending ADAM.  Please let me know if you are still looking at this.

**Comment by pkondratyuk** [comment]
Hi,
We are no longer using that code.
Thanks,
Peter

**Comment by fnothaft** [comment]
Thanks @pkondratyuk!

**Comment by xchen97** [comment]
I am using the recent version of adam-cli_2.10-0.18.1-SNAPSHOT.jar and had the similar issue running actions such as count_kmers, adam2vcf.
Here are part of the error output:
Caused by: java.lang.ClassCastException: org.apache.avro.generic.GenericData$Record cannot be cast to org.bdgenomics.formats.avro.Genotype
	at org.bdgenomics.adam.rdd.variation.GenotypeRDDFunctions$$anonfun$10.apply(VariationRDDFunctions.scala:151)
	at org.apache.spark.rdd.RDD$$anonfun$keyBy$1$$anonfun$apply$52.apply(RDD.scala:1461)
	at org.apache.spark.rdd.RDD$$anonfun$keyBy$1$$anonfun$apply$52.apply(RDD.scala:1461)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.insertAll(BypassMergeSortShuffleWriter.java:119)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Nov 16, 2015 4:35:41 PM INFO: org.apache.parquet.hadoop.ParquetInputFormat: Total input paths to process : 79

**Comment by massie** [comment]
It appears you are trying to load an ADAM file with AlignmentRecords and convert it to the VCF format. That is not a supported operation. You need to load an ADAM file with Genotype records in order to generate VCF.
-
Matt

**Comment by xchen97** [comment]
Thanks Matt.

Is there a variant calling function I can use to generate VCF file from an ADAM file with AlignmentRecords?

**Comment by xchen97** [comment]
I re-tested with the included test file "small.sam", transform works but got the same error with flagstat. Any doc or debug tool can also be helpful here?

**Comment by xchen97** [comment]
Hi Matt, the issue seems caused by Spark 1.5.2. Can you please take a look into it? Thx

**Comment by fnothaft** [comment]
Thanks for the ping @xchen97. I've been looking into this the last few days. It appears that somewhere between Spark 1.4 and Spark 1.5, Spark added a dependency on avro-ipc:1.7.7. This seems to be causing issues with the format schemas. I've opened https://github.com/bigdatagenomics/bdg-formats/pull/69 to move the formats to 1.7.7 but haven't been able to run tests yet to determine whether this fixes the issue. We should have a resolution soon.
