### ISSUE TITLE
BQSR throws error if VCF is not provided in Transform

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#456]
If you do not provide a VCF file with known sites to BQSR, it throws an error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Can not create a Path from a null string
        at org.apache.hadoop.fs.Path.checkPathArg(Path.java:123)
        at org.apache.hadoop.fs.Path.<init>(Path.java:135)
        at org.apache.spark.SparkContext.newAPIHadoopFile(SparkContext.scala:638)
        at org.bdgenomics.adam.rdd.variation.VariationContext.adamVCFLoad(VariationContext.scala:48)
        at org.bdgenomics.adam.cli.Transform.run(Transform.scala:133)
        at org.bdgenomics.adam.cli.ADAMSparkCommand$class.run(ADAMCommand.scala:58)
        at org.bdgenomics.adam.cli.Transform.run(Transform.scala:90)
        at org.bdgenomics.adam.cli.ADAMMain$.main(ADAMMain.scala:96)
        at org.bdgenomics.adam.cli.ADAMMain.main(ADAMMain.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:328)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by fnothaft** [comment]
Closed by #567.
