### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/bdgenomics/formats/avro/Feature

### ISSUE THREAD

**Issue by antonkulaga** [bigdatagenomics/adam#541]
I created a test app to learn adam ( https://github.com/antonkulaga/gene-expressions ) that only opens gtf file , reads some props and writes to a file in local filesystem.

I started spark standalone and packaged and send the app by sbt and received
```
2015-01-09 00:00:13 WARN  TaskSetManager:71 - Lost task 1.0 in stage 0.0 (TID 1, 192.168.1.105): java.lang.NoClassDefFoundError: org/bdgenomics/formats/avro/Feature
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.getDeclaredMethod(Class.java:2120)
	at java.io.ObjectStreamClass.getPrivateMethod(ObjectStreamClass.java:1431)
	at java.io.ObjectStreamClass.access$1700(ObjectStreamClass.java:72)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:494)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:468)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:468)
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:365)
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:602)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:62)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:87)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:57)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.bdgenomics.formats.avro.Feature
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more

2015-01-09 00:00:13 ERROR TaskSchedulerImpl:75 - Lost executor 0 on 192.168.1.105: remote Akka client disassociated
2015-01-09 00:00:13 WARN  ReliableDeliverySupervisor:71 - Association with remote system [akka.tcp://sparkExecutor@192.168.1.105:45450] has failed, address is now gated for [5000] ms. Reason is: [Disassociated].
```

I do not know why it happens as avro dependecies should be resolved from adam artifact. Maybe some additional spark configuration is required ...

**Comment by fnothaft** [comment]
> I do not know why it happens as avro dependecies should be resolved from adam artifact. Maybe some additional spark configuration is required ...

IIRC, you can't rely on the transitive dependency from ADAM for the avro artifacts; you should depend on the `bdg-formats` project as well. However, I looked at your downstream project and it looks like you are doing this right now. Can you post the classpath you are using and/or the spark-submit command line you are running?

**Comment by antonkulaga** [comment]
I do not use any submit scripts, I just do assembly of jar and run the project ( sbt assembly and sbt run commands respectively). When I execute run command it sends packaged jar to the server. Such approach works well in other projects with standalone spark, but for unknown reasons it does not work with adam.

Regarding Java version, I use Oracle JDK 8 on Ubuntu to build the project. I do not build adam, I just use latest snapshot.

**Comment by fnothaft** [comment]
@antonkulaga sorry for the slow reply here; I was out of town last week. What is the classpath you are using here? In parallel, I'll take a look at the ADAM artifact JAR to see if it packages in the org.bdgenomics.format.avro.* classes.

**Comment by antonkulaga** [comment]
I managed to run it successfully with spark-submit. I used to run it by just "sbt run" but @andypetrella explained me that spark-submit is more reliable.

**Comment by fnothaft** [comment]
@antonkulaga wonderful! Glad to hear the problem is resolved.
