### ISSUE TITLE
vcf2adam NoSuchMethodError on windows7/2008

### ISSUE THREAD

**Issue by simplelive** [bigdatagenomics/adam#644]
Adam: 
    adam-distribution-0.16.0-bin.zip

Spark:
    spark-1.3.0-bin-hadoop2.4.tgz

Scala:
    2.11.6

D:\data>adam vcf2adam small.vcf small.adam
Exception in thread "main" java.lang.NoSuchMethodError: scala.runtime.BooleanRef.create(Z)Lscala/runtime/BooleanRef;
        at akka.util.SubclassifiedIndex.innerAddValue(SubclassifiedIndex.scala:120)
        at akka.util.SubclassifiedIndex.addValue(SubclassifiedIndex.scala:117)
        at akka.event.SubchannelClassification$class.subscribe(EventBus.scala:147)
        at akka.event.EventStream.subscribe(EventStream.scala:46)
        at akka.event.EventStream.subscribe(EventStream.scala:26)
        at akka.event.LoggingBus$$anonfun$setUpStdoutLogger$3.apply(Logging.scala:76)
        at akka.event.LoggingBus$$anonfun$setUpStdoutLogger$3.apply(Logging.scala:76)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at akka.event.LoggingBus$class.setUpStdoutLogger(Logging.scala:76)
        at akka.event.LoggingBus$class.startStdoutLogger(Logging.scala:87)
        at akka.event.EventStream.startStdoutLogger(EventStream.scala:26)
        at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:571)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:141)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:118)
        at org.apache.spark.util.AkkaUtils$.org$apache$spark$util$AkkaUtils$$doCreateActorSystem(AkkaUtils.scala:121)
        at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:54)
        at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:53)
        at org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Utils.scala:1676)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
        at org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:1667)
        at org.apache.spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:56)
        at org.apache.spark.SparkEnv$.create(SparkEnv.scala:206)
        at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:159)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:232)
        at org.bdgenomics.adam.cli.ADAMSparkCommand$class.run(ADAMCommand.scala:54)
        at org.bdgenomics.adam.cli.Vcf2ADAM.run(Vcf2ADAM.scala:54)
        at org.bdgenomics.adam.cli.ADAMMain$.main(ADAMMain.scala:111)
        at org.bdgenomics.adam.cli.ADAMMain.main(ADAMMain.scala)

D:\data>scala
Welcome to Scala version 2.11.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_75).
Type in expressions to have them evaluated.
Type :help for more information.

scala>

**Comment by fnothaft** [comment]
ADAM is built for Scala 2.10 and should not be assumed to run on Scala 2.11 streams.

**Comment by heuermh** [comment]
As of ADAM version 0.17, separate Scala 2.10 and Scala 2.11 distributions are provided.
