### ISSUE TITLE
Requirement failed warning while running BQSR @DecadentRead

### ISSUE THREAD

**Issue by Jaeki** [bigdatagenomics/adam#646]
When running BQSR with the following command,

adam-submit transform /small.adam /small_bqsr.adam -recalibrate_base_qualities -known_snps /db/dbsnp_137.hg19.excluding_sites_after_129.vcf --master yarn-client --num-executors 85

I still got the following 'requirement failed Error' in the DecadentRead and there is no output for the BQSR.

15/04/09 13:58:17 WARN TaskSetManager: Lost task 0.0 in stage 1.0 (TID 18, node-119): java.lang.IllegalArgumentException: Error "requirement failed: sequence and qualityScores must be same length" while constructing DecadentRead from Read({"contig": {"contigName": "1", "contigLength": 249250621, "contigMD5": null, "referenceURL": null, "assembly": null, "species": null}, "start": 26472783, "oldPosition": null, "end": 26472858, "mapq": 60, "readName": "simread:1:26472783:false", "sequence": "GTATAAGAGCAGCCTTATTCCTATTTATAATCAGGGTGAAACACCTGTGCCAATGCCAAGACAGGGGTGCCAAGA", "qual": "*", "cigar": "75M", "oldCigar": null, "basesTrimmedFromStart": 0, "basesTrimmedFromEnd": 0, "readPaired": false, "properPair": false, "readMapped": true, "mateMapped": false, "firstOfPair": false, "secondOfPair": false, "failedVendorQualityChecks": false, "duplicateRead": false, "readNegativeStrand": true, "mateNegativeStrand": false, "primaryAlignment": true, "secondaryAlignment": false, "supplementaryAlignment": false, "mismatchingPositions": null, "origQual": null, "attributes": "XS:i:0\tAS:i:75\tNM:i:0", "recordGroupName": null, "recordGroupSequencingCenter": null, "recordGroupDescription": null, "recordGroupRunDateEpoch": null, "recordGroupFlowOrder": null, "recordGroupKeySequence": null, "recordGroupLibrary": null, "recordGroupPredictedMedianInsertSize": null, "recordGroupPlatform": null, "recordGroupPlatformUnit": null, "recordGroupSample": null, "mateAlignmentStart": null, "mateAlignmentEnd": null, "mateContig": null})
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:40)
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:32)
	at org.bdgenomics.adam.rich.DecadentRead$$anonfun$cloy$1.apply(DecadentRead.scala:50)
	at org.bdgenomics.adam.rich.DecadentRead$$anonfun$cloy$1.apply(DecadentRead.scala:50)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:389)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$22.apply(RDD.scala:901)
	at org.apache.spark.rdd.RDD$$anonfun$22.apply(RDD.scala:901)
	at org.apache.spark.SparkContext$$anonfun$29.apply(SparkContext.scala:1355)
	at org.apache.spark.SparkContext$$anonfun$29.apply(SparkContext.scala:1355)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: requirement failed: sequence and qualityScores must be same length
	at scala.Predef$.require(Predef.scala:233)
	at org.bdgenomics.adam.rich.DecadentRead.<init>(DecadentRead.scala:61)
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:36)
	... 23 more

**Comment by massie** [comment]
The relevant line here is `requirement failed: sequence and qualityScores must be same length`. The BAM used for input has an invalid read.

For future work, we should have an option that write invalid reads to a separate output file instead of fast failing.

**Comment by fnothaft** [comment]
This isn't an invalid read; `*` is a legal quality score string. This is a bug in BQSR; the read should be skipped instead. Let me put together a pull request to special case this.

**Comment by massie** [comment]
You're right, Frank. Good catch! I zeroed in on the error and didn't look at actual data above it.

Here's the relevant snippet from the SAM spec.

```
QUAL: ASCII of base QUALity plus 33 (same as the quality string in the Sanger FASTQ format). 
A base quality is the phred-scaled base error probability which equals −10 log10 Pr{base is wrong}. 
This field can be a ‘*’ when quality is not stored. If not a ‘*’, SEQ must not be a ‘*’ and the
length of the quality string ought to equal the length of SEQ.
```
