### ISSUE TITLE
Next on empty iterator in BroadcastRegionJoin

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#661]
Not sure why this is happening, but I'm getting this:

```
java.util.NoSuchElementException: next on empty iterator
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
        at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:64)
        at scala.collection.IterableLike$class.head(IterableLike.scala:91)
        at scala.collection.mutable.ArrayBuffer.scala$collection$IndexedSeqOptimized$$super$head(ArrayBuffer.scala:47)
        at scala.collection.IndexedSeqOptimized$class.head(IndexedSeqOptimized.scala:120)
        at scala.collection.mutable.ArrayBuffer.head(ArrayBuffer.scala:47)
        at org.bdgenomics.adam.rdd.BroadcastRegionJoin$$anonfun$4.apply(BroadcastRegionJoin.scala:114)
        at org.bdgenomics.adam.rdd.BroadcastRegionJoin$$anonfun$4.apply(BroadcastRegionJoin.scala:114)
```

It is coming from [this line](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/BroadcastRegionJoin.scala#L114):

```
// each element of the left-side RDD should have exactly one partition.
    val smallerKeyed: RDD[(ReferenceRegion, (ReferenceRegion, T))] =
      baseRDD.map(t => (regions.value.regionsFor(t).head, t))
```

I'm not sure exactly what's going on here. I've made a local hack to get my code to run that changes this to an optional `flatMap`, which lets things run forward; I'll take more of a look later this week. @tdanford do you have any intuition as to what the single-partition invariant is here? I'm thinking that this should be changed to either a `flatMap` with a log warning, or at least a more clear assert message (the stack trace isn't terribly helpful).

**Comment by fnothaft** [comment]
WAR code is at: https://github.com/bigdatagenomics/adam/tree/broadcast-join-bug

**Comment by pgrosu** [comment]
Could it be because of something similar to this:

http://stackoverflow.com/questions/28274165/scala-code-crashing-with-java-util-nosuchelementexception-next-on-empty-iterato

**Comment by fnothaft** [comment]
@pgrosu Sorry if things were unclear; that's not what I'm asking. There's an "exactly-one" invariant in the code that is being violated. There's no assert checking the "exactly-one" invariant, but the invariant is documented in the code. So yes, the exception is thrown because we're calling `head` on an empty iterator, but the bug is that the iterator is supposed to be guaranteed to have a single element in it.

**Comment by pgrosu** [comment]
Ah, okay - no problem :)  

Thanks for the clarification,
~p

**Comment by fnothaft** [comment]
The section of code impacted by this bug was removed in https://github.com/bigdatagenomics/adam/pull/1234. Closing.
