### ISSUE TITLE
upgrade to Spark 1.3.1

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#665]
any reason not to?

**Comment by fnothaft** [comment]
+1, I've moved to it for testing. I'll spin up a cluster tomorrow and run NA12878 through the base transform stages to verify that ADAM runs OK on 1.3.1.

**Comment by ryan-williams** [comment]
trying to run tests with a 35fbbb6a13ae5e8db142bec473e758fde729b3b2 ADAM against `1.3.1`, and seeing many errors like:

```
- test OP and OC tags *** FAILED ***
  java.lang.reflect.InvocationTargetException:
  at sun.reflect.GeneratedConstructorAccessor31.newInstance(Unknown Source)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
  at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:187)
  at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:181)
  at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
  at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
  at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
  at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
  at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
  ...
  Cause: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
  at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:457)
  at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:379)
  at org.apache.spark.metrics.sink.MetricsServlet.<init>(MetricsServlet.scala:45)
  at sun.reflect.GeneratedConstructorAccessor31.newInstance(Unknown Source)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
  at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:187)
  at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:181)
  at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
  at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
  ...
```

presumably some kind of jackson dep version conflict. digging…

**Comment by ryan-williams** [comment]
are there other dependencies we should be thinking about trying to get to the latest version of, in preparation for an imminent release?
