### ISSUE TITLE
fasta2adam fails on hg37d5 reference genome

### ISSUE THREAD

**Issue by llevar** [bigdatagenomics/adam#739]
Adam master, HDFS 2.6, Spark 1.3

Command - bin/adam-submit fasta2adam ~/data/reference/genome.fa hdfs://localhost:9000/data/reference/genome.fa.adam --conf spark.driver.memory=8g --conf spark.executor.memory=8g

Causes stacktrace:

24-Jul-2015 2:58:57 AM INFO: org.apache.parquet.hadoop.InternalParquetRecordWriter: Flushing mem 2015-07-24 02:59:01 ERROR Executor:96 - Exception in task 24.0 in stage 2.0 (TID 214)
java.lang.IllegalArgumentException: You cannot call toBytes() more than once without calling reset()
	at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:55)
	at org.apache.parquet.column.values.rle.RunLengthBitPackingHybridEncoder.toBytes(RunLengthBitPackingHybridEncoder.java:257)
	at org.apache.parquet.column.values.rle.RunLengthBitPackingHybridValuesWriter.getBytes(RunLengthBitPackingHybridValuesWriter.java:67)
	at org.apache.parquet.column.impl.ColumnWriterV1.writePage(ColumnWriterV1.java:152)
	at org.apache.parquet.column.impl.ColumnWriterV1.flush(ColumnWriterV1.java:240)
	at org.apache.parquet.column.impl.ColumnWriteStoreV1.flush(ColumnWriteStoreV1.java:126)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:154)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:113)
	at org.apache.parquet.hadoop.ParquetRecordWriter.close(ParquetRecordWriter.java:112)
	at org.apache.spark.rdd.InstrumentedRecordWriter.close(InstrumentedOutputFormat.scala:60)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$12.apply(PairRDDFunctions.scala:1007)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$12.apply(PairRDDFunctions.scala:979)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by heuermh** [comment]
To clarify, by hg37d5, do you mean the GRC Human Build 37 patch release 5 (GRCh37.p5)?

ftp://ftp.ncbi.nlm.nih.gov/genbank/genomes/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh37.p5/Primary_Assembly/assembled_chromosomes/FASTA/

**Comment by llevar** [comment]
Hi, It's this reference

ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/

i.e. the GRC Build 37 genome with decoy sequences from the 100 GP project.

**Comment by heuermh** [comment]
Great, thanks!  I'll take a look at this tomorrow.

**Comment by heuermh** [comment]
This works ok for me locally (i.e. without writing to HDFS) with Spark 1.3.1, Hadoop 2.6, Scala 2.10.5, and ADAM git head
```bash
$ ./bin/adam-submit fasta2adam \
  ~/ref/hs37d5.fa ~/ref/hs37d5.fa.adam \
  --conf spark.driver.memory=8g --conf spark.executor.memory=8g
...

$ ./bin/adam-submit print ~/ref/hs37d5.fa.adam | head -n 1 | jq '.'
{
  "contig": {
    "contigName": "3",
    "contigLength": 198022430,
    "contigMD5": null,
    "referenceURL": null,
    "assembly": null,
    "species": null
  },
  "description": "dna:chromosome chromosome:GRCh37:3:1:198022430:1",
  "fragmentSequence": "NN...NN",
  "fragmentNumber": 0,
  "fragmentStartPosition": 0,
  "numberOfFragmentsInContig": 19803
}
```
I still have yet to attempt in a clustered environment with HDFS.

**Comment by heuermh** [comment]
@llevar are you still having this issue?

**Comment by llevar** [comment]
Hi Michael,

I haven't touched ADAM in a couple of months frankly.

Feel free to close if you don't want to pursue this issue further.

**Comment by heuermh** [comment]
Thank you for the reply.  Please let us know if you run into this again.
