### ISSUE TITLE
git-commit-id-plugin fails homebrew --HEAD build

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#807]
```bash
$ brew install --verbose --debug --HEAD adam.rb
...
[info] dotGitDirectory /tmp/adam20150825-432-1ojk461/.git
[info] git.build.user.name Unknown
[info] git.build.user.email Unknown
[info] git.branch master
[info] Tag refs [ [] ]
[info] Created map: [ {} ] 
[info] HEAD is [ 9bf6942bc5c34245292a780896c7fbe7ef408f2e ] 
[info] Repo is in dirty state [ true ]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ADAM_2.10 .......................................... SUCCESS [01:19 min]
[INFO] ADAM_2.10: Core .................................... FAILURE [02:10 min]
[INFO] ADAM_2.10: APIs for Java ........................... SKIPPED
[INFO] ADAM_2.10: CLI ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:31 min
[INFO] Finished at: 2015-08-25T16:24:42+00:00
[INFO] Final Memory: 22M/221M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.9:revision
(default) on project adam-core_2.10: Execution default of goal
pl.project13.maven:git-commit-id-plugin:2.1.9:revision failed:
Unable to find commits until some tag: Walk failure.
Missing commit 4fd82e61f8ee1af483613400f4680fa98fa05242 -> [Help 1]
```

**Comment by heuermh** [comment]
Reopening, now failing with similar error message but different stack trace
```bash
$ brew install --verbose --debug --HEAD adam.rb
...
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - dotGitDirectory /tmp/adam20150827-150-1hr5mix/.git
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - git.build.user.name 
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - git.build.user.email 
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - git.branch master
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - --always = true
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - --dirty = -dirty
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - --abbrev = 7
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - Tag refs [ [] ]
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - Created map: [ {} ] 
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - HEAD is [ b987dcc67b839c91eff81af2448291b547924ba4 ] 
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - Repo is in dirty state [ true ]
java.lang.RuntimeException: Unable to find commits until some tag
	at pl.project13.jgit.JGitCommon.findCommitsUntilSomeTag(JGitCommon.java:286)
	at pl.project13.jgit.DescribeCommand.call(DescribeCommand.java:298)
	at pl.project13.maven.git.JGitProvider.getGitDescribe(JGitProvider.java:234)
	at pl.project13.maven.git.JGitProvider.getGitDescribe(JGitProvider.java:125)
	at pl.project13.maven.git.GitDataProvider.maybePutGitDescribe(GitDataProvider.java:139)
	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:104)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:585)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:558)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:376)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.jgit.errors.RevWalkException: Walk failure.
	at org.eclipse.jgit.revwalk.RevWalk.iterator(RevWalk.java:1306)
	at pl.project13.jgit.JGitCommon.findCommitsUntilSomeTag(JGitCommon.java:274)
	... 30 more
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing commit 5432a61c0241519b390ad31569cd965a9b604b0b
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:149)
	at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:884)
	at org.eclipse.jgit.revwalk.RevCommit.parseHeaders(RevCommit.java:145)
	at org.eclipse.jgit.revwalk.PendingGenerator.next(PendingGenerator.java:148)
	at org.eclipse.jgit.revwalk.StartGenerator.next(StartGenerator.java:186)
	at org.eclipse.jgit.revwalk.RevWalk.next(RevWalk.java:422)
	at org.eclipse.jgit.revwalk.RevWalk.iterator(RevWalk.java:1304)
	... 31 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ADAM_2.10 .......................................... SUCCESS [ 57.376 s]
[INFO] ADAM_2.10: Core .................................... FAILURE [01:38 min]
[INFO] ADAM_2.10: APIs for Java ........................... SKIPPED
[INFO] ADAM_2.10: CLI ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by heuermh** [comment]
Fixed by using ```:shallow => false``` in the head git clone url, see https://github.com/Homebrew/homebrew-science/pull/2738.
