### ISSUE TITLE
adam appassembler script required but does not run

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#808]
The appassembler script ```adam``` is required for the other scripts
```bash
$ brew install --verbose --debug adam.rb
==> Finishing up
ln -s ../Cellar/adam/0.17.1/bin/adam-pyspark adam-pyspark
ln -s ../Cellar/adam/0.17.1/bin/adam-shell adam-shell
ln -s ../Cellar/adam/0.17.1/bin/adam-submit adam-submit
ln -s ../Cellar/adam/0.17.1/bin/append_to_option.py append_to_option.py
ln -s ../Cellar/adam/0.17.1/bin/compute-adam-classpath.sh compute-adam-classpath.sh
ln -s ../Cellar/adam/0.17.1/bin/compute-adam-jars.sh compute-adam-jars.sh
==> Summary
/home/linuxbrew/.linuxbrew/Cellar/adam/0.17.1: 512 files, 64M, built in 14 seconds

$ adam-submit
Failed to find appassembler scripts in /bin
You need to build ADAM before running this program
```

I don't like the idea of installing something to the user's path that only throws an exception
```bash
$ brew install --verbose --debug adam.rb
==> Finishing up
ln -s ../Cellar/adam/0.17.1/bin/adam adam
ln -s ../Cellar/adam/0.17.1/bin/adam-pyspark adam-pyspark
ln -s ../Cellar/adam/0.17.1/bin/adam-shell adam-shell
ln -s ../Cellar/adam/0.17.1/bin/adam-submit adam-submit
ln -s ../Cellar/adam/0.17.1/bin/append_to_option.py append_to_option.py
ln -s ../Cellar/adam/0.17.1/bin/compute-adam-classpath.sh compute-adam-classpath.sh
ln -s ../Cellar/adam/0.17.1/bin/compute-adam-jars.sh compute-adam-jars.sh
==> Summary
/home/linuxbrew/.linuxbrew/Cellar/adam/0.17.1: 514 files, 64M, built in 49 seconds

$ adam
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/Logging
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.bdgenomics.adam.cli.ADAMMain.main(ADAMMain.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.Logging
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 13 more

$ adam-submit
Using SPARK_SUBMIT=/home/linuxbrew/.linuxbrew/bin/spark-submit
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
15/08/25 16:19:19 INFO ADAMMain: ADAM invoked with args: 


     e            888~-_              e                 e    e
    d8b           888   \            d8b               d8b  d8b
   /Y88b          888    |          /Y88b             d888bdY88b
  /  Y88b         888    |         /  Y88b           / Y88Y Y888b
 /____Y88b        888   /         /____Y88b         /   YY   Y888b
/      Y88b       888_-~         /      Y88b       /          Y888b

Usage: adam-submit [<spark-args> --] <adam-args>
...
```

**Comment by heuermh** [comment]
Two possible approaches:
 * Add a new main class without external dependencies that displays an informational message redirecting the user to call either ```adam-submit``` or ```adam-shell```
 * Build a fat/uber jar, with maven-assembly-plugin ```jar-with-dependencies``` or maven-shade-plugin.  This should eliminate the need for ```compute-adam-classpath.sh``` and ```compute-adam-jars.sh``` scripts, which depend on the appassembler ```adam``` script

**Comment by fnothaft** [comment]
Closed by https://github.com/bigdatagenomics/adam/commit/f39de5743e2d995db0eeb22cd324e9dd87596817.
