### ISSUE TITLE
Transform -limit_projection requires .sam.seqdict file

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#937]
ADAM transform of SAM or BAM formatted files with ```-limit_projection``` option throws difficult to interpret error message about missing ```.{sam,bam}.seqdict``` file.

```bash
$ ./bin/adam-submit transform adam-core/src/test/resources/small.sam -limit_projection small-limit.adam
Using ADAM_MAIN=org.bdgenomics.adam.cli.ADAMMain
Using SPARK_SUBMIT=/usr/local/bin/spark-submit
2016-02-10 13:20:25 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Command body threw exception:
java.io.FileNotFoundException: File adam-core/src/test/resources/small.sam.seqdict does not exist
Exception in thread "main" java.io.FileNotFoundException: File adam-core/src/test/resources/small.sam.seqdict does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:534)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:747)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:524)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:409)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:140)
	at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:341)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:766)
	at org.bdgenomics.adam.rdd.ADAMContext.loadAvro(ADAMContext.scala:401)
	at org.bdgenomics.adam.rdd.ADAMContext.loadParquetAlignments(ADAMContext.scala:477)
	at org.bdgenomics.adam.cli.Transform.run(Transform.scala:264)
	at org.bdgenomics.utils.cli.BDGSparkCommand$class.run(BDGCommand.scala:54)
	at org.bdgenomics.adam.cli.Transform.run(Transform.scala:119)
	at org.bdgenomics.adam.cli.ADAMMain.apply(ADAMMain.scala:136)
	at org.bdgenomics.adam.cli.ADAMMain$.main(ADAMMain.scala:76)
	at org.bdgenomics.adam.cli.ADAMMain.main(ADAMMain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by fnothaft** [comment]
The `-limit_projection` switch only works on Parquet files. Perhaps we should log a warning message if we're have a file that ends in `.sam`/`.bam`.

**Comment by heuermh** [comment]
+1, that what I was thinking
