### ISSUE TITLE
Exception occurs when running tests on master

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#956]
On `master`, an exception is logged to the console when building with mvn `mvn clean package`
 when running tests, as listed below.  However, maven still reports full SUCCESS of the build.
```
- convert an RDD that has an bad read in it with loose validation
2016-02-23 16:17:47 WARN  MetricsSystem:71 - Using default name DAGScheduler for source because spark.app.id is not set.
2016-02-23 16:17:47 ERROR Executor:96 - Exception in task 1.0 in stage 0.0 (TID 1)
java.lang.IllegalArgumentException: Error "(D,Some(3)) (of class scala.Tuple2)" while constructing DecadentRead from Read({"readInFragment": 0, "contig": {"contigName": "1", "contigLength": null, "contigMD5": null, "referenceURL": null, "assembly": null, "species": null, "referenceIndex": null}, "start": 248262648, "oldPosition": null, "end": 248262721, "mapq": 23, "readName": null, "sequence": "GATCTTTTCAACAGTTACAGCAGAAAGTTTTCATGGAGAAATGGAATCACACTTCAAATGATTTCATTTTGTTGGG", "qual": "IBBHEFFEKFCKFHFACKFIJFJDCFHFEEDJBCHIFIDDBCGJDBBJAJBJFCIDCACHBDEBHADDDADDAED;", "cigar": "4S1M1D71M", "oldCigar": null, "basesTrimmedFromStart": 0, "basesTrimmedFromEnd": 0, "readPaired": false, "properPair": false, "readMapped": true, "mateMapped": false, "failedVendorQualityChecks": false, "duplicateRead": false, "readNegativeStrand": false, "mateNegativeStrand": false, "primaryAlignment": false, "secondaryAlignment": false, "supplementaryAlignment": false, "mismatchingPositions": "3^C71", "origQual": null, "attributes": null, "recordGroupName": null, "recordGroupSample": null, "mateAlignmentStart": null, "mateAlignmentEnd": null, "mateContig": null, "inferredInsertSize": null})
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:42)
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:34)
	at org.bdgenomics.adam.rich.DecadentRead$$anonfun$cloy$1.apply(DecadentRead.scala:57)
	at org.bdgenomics.adam.rich.DecadentRead$$anonfun$cloy$1.apply(DecadentRead.scala:55)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.util.Utils$.getIteratorSize(Utils.scala:1555)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1125)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1125)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1850)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1850)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: scala.MatchError: (D,Some(3)) (of class scala.Tuple2)
	at org.bdgenomics.adam.util.MdTag$.apply(MdTag.scala:71)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.mdTag$lzycompute(RichAlignmentRecord.scala:98)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.mdTag(RichAlignmentRecord.scala:96)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.getReferenceBase$1(RichAlignmentRecord.scala:176)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.getReferenceContext(RichAlignmentRecord.scala:192)
	at org.bdgenomics.adam.rich.RichAlignmentRecord$$anonfun$1$$anonfun$2.apply(RichAlignmentRecord.scala:213)
	at org.bdgenomics.adam.rich.RichAlignmentRecord$$anonfun$1$$anonfun$2.apply(RichAlignmentRecord.scala:211)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.bdgenomics.adam.rich.RichAlignmentRecord$$anonfun$1.apply(RichAlignmentRecord.scala:211)
	at org.bdgenomics.adam.rich.RichAlignmentRecord$$anonfun$1.apply(RichAlignmentRecord.scala:200)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.referenceContexts$lzycompute(RichAlignmentRecord.scala:200)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.referenceContexts(RichAlignmentRecord.scala:198)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.referencePositions$lzycompute(RichAlignmentRecord.scala:196)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.referencePositions(RichAlignmentRecord.scala:196)
	at org.bdgenomics.adam.rich.DecadentRead.<init>(DecadentRead.scala:94)
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:38)
	... 15 more
2016-02-23 16:17:47 WARN  TaskSetManager:71 - Lost task 1.0 in stage 0.0 (TID 1, localhost): java.lang.IllegalArgumentException: Error "(D,Some(3)) (of class scala.Tuple2)" while constructing DecadentRead from Read({"readInFragment": 0, "contig": {"contigName": "1", "contigLength": null, "contigMD5": null, "referenceURL": null, "assembly": null, "species": null, "referenceIndex": null}, "start": 248262648, "oldPosition": null, "end": 248262721, "mapq": 23, "readName": null, "sequence": "GATCTTTTCAACAGTTACAGCAGAAAGTTTTCATGGAGAAATGGAATCACACTTCAAATGATTTCATTTTGTTGGG", "qual": "IBBHEFFEKFCKFHFACKFIJFJDCFHFEEDJBCHIFIDDBCGJDBBJAJBJFCIDCACHBDEBHADDDADDAED;", "cigar": "4S1M1D71M", "oldCigar": null, "basesTrimmedFromStart": 0, "basesTrimmedFromEnd": 0, "readPaired": false, "properPair": false, "readMapped": true, "mateMapped": false, "failedVendorQualityChecks": false, "duplicateRead": false, "readNegativeStrand": false, "mateNegativeStrand": false, "primaryAlignment": false, "secondaryAlignment": false, "supplementaryAlignment": false, "mismatchingPositions": "3^C71", "origQual": null, "attributes": null, "recordGroupName": null, "recordGroupSample": null, "mateAlignmentStart": null, "mateAlignmentEnd": null, "mateContig": null, "inferredInsertSize": null})
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:42)
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:34)
	at org.bdgenomics.adam.rich.DecadentRead$$anonfun$cloy$1.apply(DecadentRead.scala:57)
	at org.bdgenomics.adam.rich.DecadentRead$$anonfun$cloy$1.apply(DecadentRead.scala:55)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.util.Utils$.getIteratorSize(Utils.scala:1555)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1125)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1125)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1850)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1850)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: scala.MatchError: (D,Some(3)) (of class scala.Tuple2)
	at org.bdgenomics.adam.util.MdTag$.apply(MdTag.scala:71)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.mdTag$lzycompute(RichAlignmentRecord.scala:98)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.mdTag(RichAlignmentRecord.scala:96)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.getReferenceBase$1(RichAlignmentRecord.scala:176)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.getReferenceContext(RichAlignmentRecord.scala:192)
	at org.bdgenomics.adam.rich.RichAlignmentRecord$$anonfun$1$$anonfun$2.apply(RichAlignmentRecord.scala:213)
	at org.bdgenomics.adam.rich.RichAlignmentRecord$$anonfun$1$$anonfun$2.apply(RichAlignmentRecord.scala:211)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.bdgenomics.adam.rich.RichAlignmentRecord$$anonfun$1.apply(RichAlignmentRecord.scala:211)
	at org.bdgenomics.adam.rich.RichAlignmentRecord$$anonfun$1.apply(RichAlignmentRecord.scala:200)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.referenceContexts$lzycompute(RichAlignmentRecord.scala:200)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.referenceContexts(RichAlignmentRecord.scala:198)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.referencePositions$lzycompute(RichAlignmentRecord.scala:196)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.referencePositions(RichAlignmentRecord.scala:196)
	at org.bdgenomics.adam.rich.DecadentRead.<init>(DecadentRead.scala:94)
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:38)
	... 15 more

```

**Comment by fnothaft** [comment]
That exception gets thrown from [hereabouts](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/test/scala/org/bdgenomics/adam/rich/DecadentReadSuite.scala#L107) in a test that is checking that a requirement fires when enriching an `RDD[AlignmentRecord]` to `RDD[DecadentRead]`. This is expected behavior, but yes, it does occasionally cause one to do a doubletake.
